In [1]:
import os
import pandas as pd
import numpy as np
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
df = pd.read_csv('/Users/prafulchunchu/Desktop/Duke/AIPI510/moduleProj1/module_project_1/data/raw/export.csv')
cvd = df.loc[df['Topic'] == 'Cardiovascular Disease']
cvd['Question'].unique()

ct = pd.crosstab(df['Topic'], df['DataSource'])

ct

/var/folders/gh/wsxft4xn39x_512_wsyp_9bc0000gn/T/ipykernel_44602/126542413.py:7: DtypeWarning: Columns (10,11,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/prafulchunchu/Desktop/Duke/AIPI510/moduleProj1/module_project_1/data/raw/export.csv')

DataSource,ACS,AEDS,ANRF,BRFSS,CMS Part A Claims Data,Current Population Survey - FSS,NIS,NSCH,NVSS,PRAMS,US Cancer DVT,USRDS,WIC Participant and Program Characteristics,YRBSS
Topic,,,,,,,,,,,,,,
Alcohol,0,220,0,20585,0,0,0,0,7488,0,0,0,0,4620
Arthritis,0,0,0,25190,0,0,0,0,0,0,0,0,0,0
Asthma,0,0,0,6325,0,0,0,0,7488,0,0,0,0,0
Cancer,0,0,0,3960,0,0,0,0,0,0,23472,0,0,0
Cardiovascular Disease,0,0,0,15180,4992,0,0,0,22464,0,0,0,0,0
Chronic Kidney Disease,0,0,0,0,0,0,0,0,0,0,0,416,0,0
Chronic Obstructive Pulmonary Disease,0,0,0,12650,9984,0,0,0,14144,0,0,0,0,0
Cognitive Health and Caregiving,0,0,0,9900,0,0,0,0,0,0,0,0,0,0
Diabetes,0,0,0,6325,0,0,0,0,14976,1298,0,0,0,0
Disability,0,0,0,6325,0,0,0,0,0,0,0,0,0,0
Health Status,0,0,0,31625,0,0,0,0,468,0,0,0,0,0
Immunization,0,0,0,23925,0,0,0,0,0,0,0,0,0,0
Maternal Health,0,0,0,0,0,0,0,0,0,1298,0,0,0,0
Mental Health,0,0,0,18975,0,0,0,0,0,1298,0,0,0,1610
Non-Medical Factors,4836,0,0,19965,0,110,0,0,0,2596,0,0,0,0
"Nutrition, Physical Activity, and Weight Status",0,0,0,20240,0,0,368,1872,0,0,0,0,432,9800
Oral Health,0,0,0,9350,0,0,0,2860,0,1298,0,0,0,0
Sleep,0,0,0,2530,0,0,0,1872,0,0,0,0,0,2310
Tobacco,0,0,275,12650,0,0,0,0,0,1298,0,0,0,6930

***Personal Observation:*** I've noticed that BRFSS and NVSS cover majority of the diseases or the 4  we picked, not sure why CMS is part of our interest when it only covers 2 diseases.  I suggest either changing the disease focus to 2 diseases instead of 4

In [2]:
print(df[df['DataSource']=='BRFSS']['DataValueUnit'].unique())
print(df[df['DataSource']=='NVSS']['DataValueUnit'].unique())
print(df[df['DataSource']=='CMS Part A Claims Data']['DataValueUnit'].unique())

['%' 'Number']
['Number' 'Years' 'cases per 100,000']
['Number' 'cases per 1,000']

In [3]:
# BRFSS prevalence rows that made it into the panel
mask = (df['DataSource']=='BRFSS') & (df['DataValueType']=='Age-adjusted Prevalence') & (df['Stratification1']=='Overall')
print(df[mask]['DataValueUnit'].unique())

['%']

In [4]:
# BRFSS prevalence rows that made it into the panel
mask = (df['DataSource']=='NVSS') & (df['DataValueType']=='Age-adjusted Rate') & (df['Stratification1']=='Overall')
print(df[mask]['DataValueUnit'].unique())

['cases per 100,000']

In [5]:
# BRFSS prevalence rows that made it into the panel
mask = (df['DataSource']=='CMS Part A Claims Data') & (df['DataValueType']=='Age-adjusted Rate') & (df['Stratification1']=='Overall')
print(df[mask]['DataValueUnit'].unique())

['cases per 1,000']

In [6]:
diseases_focus = ['Asthma', 'Cardiovascular Disease', 'Chronic Obstructive Pulmonary Disease', 'Diabetes']
data_sources = ['BRFSS', 'NVSS', 'CMS Part A Claims Data']

for topic in diseases_focus:
    print(f"\n{topic}:")
    sub = df.loc[(df['Topic'] == topic) & (df['DataSource'].isin(data_sources))]
    print(pd.crosstab(sub['Question'], sub['DataSource']))

Asthma:
DataSource                                           BRFSS  NVSS
Question
Asthma mortality among all people, underlying cause      0  7488
Current asthma among adults                           6325     0

Cardiovascular Disease:
DataSource                                                                                                BRFSS  \
Question
Cerebrovascular disease (stroke) mortality among all people, underlying cause                                 0
Coronary heart disease mortality among all people, underlying cause                                           0
Diseases of the heart mortality among all people, underlying cause                                            0
High blood pressure among adults                                                                           3795
High cholesterol among adults who have been screened                                                       3795
Hospitalization for heart failure as principal diagnosis, Medicare-beneficiaries aged 65 years and older      0
Taking medicine for high cholesterol among adults with high cholesterol                                    3795
Taking medicine to control high blood pressure among adults with high blood pressure                       3795

DataSource                                                                                                CMS Part A Claims Data  \
Question
Cerebrovascular disease (stroke) mortality among all people, underlying cause                                                  0
Coronary heart disease mortality among all people, underlying cause                                                            0
Diseases of the heart mortality among all people, underlying cause                                                             0
High blood pressure among adults                                                                                               0
High cholesterol among adults who have been screened                                                                           0
Hospitalization for heart failure as principal diagnosis, Medicare-beneficiaries aged 65 years and older                    4992
Taking medicine for high cholesterol among adults with high cholesterol                                                        0
Taking medicine to control high blood pressure among adults with high blood pressure                                           0

DataSource                                                                                                NVSS
Question
Cerebrovascular disease (stroke) mortality among all people, underlying cause                             7488
Coronary heart disease mortality among all people, underlying cause                                       7488
Diseases of the heart mortality among all people, underlying cause                                        7488
High blood pressure among adults                                                                             0
High cholesterol among adults who have been screened                                                         0
Hospitalization for heart failure as principal diagnosis, Medicare-beneficiaries aged 65 years and older     0
Taking medicine for high cholesterol among adults with high cholesterol                                      0
Taking medicine to control high blood pressure among adults with high blood pressure                         0

Chronic Obstructive Pulmonary Disease:
DataSource                                                                                                                        BRFSS  \
Question
Chronic obstructive pulmonary disease among adults                                                                                 6325
Chronic obstructive pulmonary disease mortality among adults aged 45 years and older, underlying cause                                0
Chronic obstructive pulmonary disease mortality among adults aged 45 years and older, underlying or contributing cause                0
Current smoking among adults with chronic obstructive pulmonary disease                                                            6325
Hospitalization for chronic obstructive pulmonary disease as any diagnosis, Medicare-beneficiaries aged 65 years and older            0
Hospitalization for chronic obstructive pulmonary disease as principal diagnosis, Medicare-beneficiaries aged 65 years and older      0

DataSource                                                                                                                        CMS Part A Claims Data  \
Question
Chronic obstructive pulmonary disease among adults                                                                                                     0
Chronic obstructive pulmonary disease mortality among adults aged 45 years and older, underlying cause                                                 0
Chronic obstructive pulmonary disease mortality among adults aged 45 years and older, underlying or contributing cause                                 0
Current smoking among adults with chronic obstructive pulmonary disease                                                                                0
Hospitalization for chronic obstructive pulmonary disease as any diagnosis, Medicare-beneficiaries aged 65 years and older                          4992
Hospitalization for chronic obstructive pulmonary disease as principal diagnosis, Medicare-beneficiaries aged 65 years and older                    4992

DataSource                                                                                                                        NVSS
Question
Chronic obstructive pulmonary disease among adults                                                                                   0
Chronic obstructive pulmonary disease mortality among adults aged 45 years and older, underlying cause                            7072
Chronic obstructive pulmonary disease mortality among adults aged 45 years and older, underlying or contributing cause            7072
Current smoking among adults with chronic obstructive pulmonary disease                                                              0
Hospitalization for chronic obstructive pulmonary disease as any diagnosis, Medicare-beneficiaries aged 65 years and older           0
Hospitalization for chronic obstructive pulmonary disease as principal diagnosis, Medicare-beneficiaries aged 65 years and older     0

Diabetes:
DataSource                                                                          BRFSS  \
Question
Diabetes among adults                                                                6325
Diabetes mortality among all people, underlying or contributing cause                   0
Diabetic ketoacidosis mortality among all people, underlying or contributing cause      0

DataSource                                                                          NVSS
Question
Diabetes among adults                                                                  0
Diabetes mortality among all people, underlying or contributing cause               7488
Diabetic ketoacidosis mortality among all people, underlying or contributing cause  7488

### Check ipad notes for the ones we decided for which data source and which question

In [7]:
diseases_focus = ['Asthma', 'Cardiovascular Disease', 'Chronic Obstructive Pulmonary Disease', 'Diabetes']
data_sources = ['BRFSS', 'NVSS', 'CMS Part A Claims Data']
cvd = df.loc[df['Topic'] == 'Cardiovascular Disease']
#print(cvd['Question'].unique())

ct = pd.crosstab(df['Topic'], df['DataSource'])

print(ct)

DataSource                                        ACS  AEDS  ANRF  BRFSS  \
Topic
Alcohol                                             0   220     0  20585
Arthritis                                           0     0     0  25190
Asthma                                              0     0     0   6325
Cancer                                              0     0     0   3960
Cardiovascular Disease                              0     0     0  15180
Chronic Kidney Disease                              0     0     0      0
Chronic Obstructive Pulmonary Disease               0     0     0  12650
Cognitive Health and Caregiving                     0     0     0   9900
Diabetes                                            0     0     0   6325
Disability                                          0     0     0   6325
Health Status                                       0     0     0  31625
Immunization                                        0     0     0  23925
Maternal Health                                     0     0     0      0
Mental Health                                       0     0     0  18975
Non-Medical Factors                              4836     0     0  19965
Nutrition, Physical Activity, and Weight Status     0     0     0  20240
Oral Health                                         0     0     0   9350
Sleep                                               0     0     0   2530
Tobacco                                             0     0   275  12650

DataSource                                       CMS Part A Claims Data  \
Topic
Alcohol                                                               0
Arthritis                                                             0
Asthma                                                                0
Cancer                                                                0
Cardiovascular Disease                                             4992
Chronic Kidney Disease                                                0
Chronic Obstructive Pulmonary Disease                              9984
Cognitive Health and Caregiving                                       0
Diabetes                                                              0
Disability                                                            0
Health Status                                                         0
Immunization                                                          0
Maternal Health                                                       0
Mental Health                                                         0
Non-Medical Factors                                                   0
Nutrition, Physical Activity, and Weight Status                       0
Oral Health                                                           0
Sleep                                                                 0
Tobacco                                                               0

DataSource                                       Current Population Survey - FSS  \
Topic
Alcohol                                                                        0
Arthritis                                                                      0
Asthma                                                                         0
Cancer                                                                         0
Cardiovascular Disease                                                         0
Chronic Kidney Disease                                                         0
Chronic Obstructive Pulmonary Disease                                          0
Cognitive Health and Caregiving                                                0
Diabetes                                                                       0
Disability                                                                     0
Health Status                                                                  0
Immunization                                                                   0
Maternal Health                                                                0
Mental Health                                                                  0
Non-Medical Factors                                                          110
Nutrition, Physical Activity, and Weight Status                                0
Oral Health                                                                    0
Sleep                                                                          0
Tobacco                                                                        0

DataSource                                       NIS  NSCH   NVSS  PRAMS  \
Topic
Alcohol                                            0     0   7488      0
Arthritis                                          0     0      0      0
Asthma                                             0     0   7488      0
Cancer                                             0     0      0      0
Cardiovascular Disease                             0     0  22464      0
Chronic Kidney Disease                             0     0      0      0
Chronic Obstructive Pulmonary Disease              0     0  14144      0
Cognitive Health and Caregiving                    0     0      0      0
Diabetes                                           0     0  14976   1298
Disability                                         0     0      0      0
Health Status                                      0     0    468      0
Immunization                                       0     0      0      0
Maternal Health                                    0     0      0   1298
Mental Health                                      0     0      0   1298
Non-Medical Factors                                0     0      0   2596
Nutrition, Physical Activity, and Weight Status  368  1872      0      0
Oral Health                                        0  2860      0   1298
Sleep                                              0  1872      0      0
Tobacco                                            0     0      0   1298

DataSource                                       US Cancer DVT  USRDS  \
Topic
Alcohol                                                      0      0
Arthritis                                                    0      0
Asthma                                                       0      0
Cancer                                                   23472      0
Cardiovascular Disease                                       0      0
Chronic Kidney Disease                                       0    416
Chronic Obstructive Pulmonary Disease                        0      0
Cognitive Health and Caregiving                              0      0
Diabetes                                                     0      0
Disability                                                   0      0
Health Status                                                0      0
Immunization                                                 0      0
Maternal Health                                              0      0
Mental Health                                                0      0
Non-Medical Factors                                          0      0
Nutrition, Physical Activity, and Weight Status              0      0
Oral Health                                                  0      0
Sleep                                                        0      0
Tobacco                                                      0      0

DataSource                                       WIC Participant and Program Characteristics  \
Topic
Alcohol                                                                                    0
Arthritis                                                                                  0
Asthma                                                                                     0
Cancer                                                                                     0
Cardiovascular Disease                                                                     0
Chronic Kidney Disease                                                                     0
Chronic Obstructive Pulmonary Disease                                                      0
Cognitive Health and Caregiving                                                            0
Diabetes                                                                                   0
Disability                                                                                 0
Health Status                                                                              0
Immunization                                                                               0
Maternal Health                                                                            0
Mental Health                                                                              0
Non-Medical Factors                                                                        0
Nutrition, Physical Activity, and Weight Status                                          432
Oral Health                                                                                0
Sleep                                                                                      0
Tobacco                                                                                    0

DataSource                                       YRBSS
Topic
Alcohol                                           4620
Arthritis                                            0
Asthma                                               0
Cancer                                               0
Cardiovascular Disease                               0
Chronic Kidney Disease                               0
Chronic Obstructive Pulmonary Disease                0
Cognitive Health and Caregiving                      0
Diabetes                                             0
Disability                                           0
Health Status                                        0
Immunization                                         0
Maternal Health                                      0
Mental Health                                     1610
Non-Medical Factors                                  0
Nutrition, Physical Activity, and Weight Status   9800
Oral Health                                          0
Sleep                                             2310
Tobacco                                           6930

In [8]:
df['DataValueType'].value_counts()

DataValueType
Crude Prevalence                                 165341
Age-adjusted Prevalence                           93830
Number                                            37412
Crude Rate                                        36736
Age-adjusted Rate                                 31536
Crude Mean                                        10725
Age-adjusted Mean                                  8250
Crude Median                                       7150
Crude 75th percentile                              7110
Proportion                                          275
Per capita alcohol consumption gallons              220
Adjusted rate by age, sex, race and ethnicity       208
Name: count, dtype: int64

In [9]:
df.dtypes

YearStart                      int64
YearEnd                        int64
LocationAbbr                  object
LocationDesc                  object
DataSource                    object
Topic                         object
Question                      object
Response                     float64
DataValueUnit                 object
DataValueType                 object
DataValue                     object
DataValueAlt                  object
DataValueFootnoteSymbol       object
DataValueFootnote             object
LowConfidenceLimit            object
HighConfidenceLimit           object
StratificationCategory1       object
Stratification1               object
StratificationCategory2      float64
Stratification2              float64
StratificationCategory3      float64
Stratification3              float64
Geolocation                   object
LocationID                     int64
TopicID                       object
QuestionID                    object
ResponseID                   float64
DataValueTypeID               object
StratificationCategoryID1     object
StratificationID1             object
StratificationCategoryID2    float64
StratificationID2            float64
StratificationCategoryID3    float64
StratificationID3            float64
dtype: object

In [10]:
df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,DataValue,DataValueAlt,DataValueFootnoteSymbol,DataValueFootnote,LowConfidenceLimit,HighConfidenceLimit,StratificationCategory1,Stratification1,StratificationCategory2,Stratification2,StratificationCategory3,Stratification3,Geolocation,LocationID,TopicID,QuestionID,ResponseID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2020,2020,AR,Arkansas,NVSS,Asthma,"Asthma mortality among all people, underlying cause",NaN,Number,Number,20,20,NaN,NaN,NaN,NaN,Sex,Female,NaN,NaN,NaN,NaN,POINT (-92.27449074 34.74865012400045),5,AST,AST01,NaN,NMBR,SEX,SEXF,NaN,NaN,NaN,NaN
1,2019,2019,IA,Iowa,NVSS,Asthma,"Asthma mortality among all people, underlying cause",NaN,Number,Number,32,32,NaN,NaN,NaN,NaN,Sex,Female,NaN,NaN,NaN,NaN,POINT (-93.81649056 42.46940091300047),19,AST,AST01,NaN,NMBR,SEX,SEXF,NaN,NaN,NaN,NaN
2,2021,2021,CO,Colorado,BRFSS,Asthma,Current asthma among adults,NaN,%,Crude Prevalence,8.1,8.1,NaN,NaN,7.2,9.0,Sex,Male,NaN,NaN,NaN,NaN,POINT (-106.1336109 38.843840757000464),8,AST,AST02,NaN,CRDPREV,SEX,SEXM,NaN,NaN,NaN,NaN
3,2023,2023,KY,Kentucky,BRFSS,Asthma,Current asthma among adults,NaN,%,Crude Prevalence,NaN,NaN,*,No data available,NaN,NaN,Age,Age >=65,NaN,NaN,NaN,NaN,POINT (-84.77497105 37.645970271000465),21,AST,AST02,NaN,CRDPREV,AGE,AGE65P,NaN,NaN,NaN,NaN
4,2023,2023,MD,Maryland,BRFSS,Asthma,Current asthma among adults,NaN,%,Crude Prevalence,10.1,10.1,NaN,NaN,8.8,11.6,Age,Age >=65,NaN,NaN,NaN,NaN,POINT (-76.60926011 39.29058096400047),24,AST,AST02,NaN,CRDPREV,AGE,AGE65P,NaN,NaN,NaN,NaN

In [11]:
cleaned_df = df.loc[df['Topic'].isin(diseases_focus)]

In [12]:
brfss_rows = df.loc[df['DataSource']=='BRFSS']
print(brfss_rows['DataValueType'].value_counts())

DataValueType
Crude Prevalence           118635
Age-adjusted Prevalence     93830
Crude Mean                  10725
Age-adjusted Mean            8250
Crude Median                 7150
Crude 75th percentile        7110
Name: count, dtype: int64

In [13]:
cleaned_df = cleaned_df.loc[cleaned_df['DataSource'].isin(data_sources)]

In [14]:
cleaned_df = cleaned_df.loc[(cleaned_df['DataValueType'].isin(['Age-adjusted Rate', 'Age-adjusted Prevalence'])) & (cleaned_df['Stratification1'] == 'Overall')]

In [15]:
cleaned_df.drop(columns=['YearEnd', 'LocationDesc', 'Response', 'DataValueUnit', 'DataValue', 'DataValueFootnoteSymbol',
                         'DataValueFootnote', 'StratificationCategory1', 'StratificationCategory2',	
                         'Stratification2',	'StratificationCategory3',	'Stratification3',
                         'Geolocation',	'LocationID',	'TopicID',	'QuestionID',	'ResponseID',	'DataValueTypeID',	
                         'StratificationCategoryID1',	'StratificationID1',	'StratificationCategoryID2',	
                         'StratificationID2',	'StratificationCategoryID3',	'StratificationID3'], inplace=True)

In [16]:
cleaned_df = cleaned_df.loc[cleaned_df['LocationAbbr'] != 'US']

In [17]:
cleaned_df = cleaned_df.reset_index(drop=True)

In [18]:
cleaned_df

,YearStart,LocationAbbr,DataSource,Topic,Question,DataValueType,DataValueAlt,LowConfidenceLimit,HighConfidenceLimit,Stratification1
0,2022,MN,NVSS,Asthma,"Asthma mortality among all people, underlying cause",Age-adjusted Rate,0.9,0.7,1.2,Overall
1,2021,IL,NVSS,Asthma,"Asthma mortality among all people, underlying cause",Age-adjusted Rate,0.9,0.8,1.1,Overall
2,2022,WY,NVSS,Asthma,"Asthma mortality among all people, underlying cause",Age-adjusted Rate,NaN,NaN,NaN,Overall
3,2020,OK,BRFSS,Asthma,Current asthma among adults,Age-adjusted Prevalence,12.1,11.0,13.3,Overall
4,2021,AL,NVSS,Asthma,"Asthma mortality among all people, underlying cause",Age-adjusted Rate,1.2,0.9,1.5,Overall
...,...,...,...,...,...,...,...,...,...,...
3967,2022,WV,NVSS,Diabetes,"Diabetic ketoacidosis mortality among all people, underlying or contributing cause",Age-adjusted Rate,3.5,2.8,4.5,Overall
3968,2020,WY,NVSS,Diabetes,"Diabetic ketoacidosis mortality among all people, underlying or contributing cause",Age-adjusted Rate,3.4,2.1,5.2,Overall
3969,2022,WA,NVSS,Diabetes,"Diabetic ketoacidosis mortality among all people, underlying or contributing cause",Age-adjusted Rate,2.6,2.3,3.0,Overall
3970,2020,WI,NVSS,Diabetes,"Diabetic ketoacidosis mortality among all people, underlying or contributing cause",Age-adjusted Rate,1.9,1.6,2.3,Overall
3971,2020,VA,NVSS,Diabetes,"Diabetic ketoacidosis mortality among all people, underlying or contributing cause",Age-adjusted Rate,1.6,1.3,1.8,Overall

In [19]:
print(cleaned_df.shape)
print(cleaned_df['Topic'].value_counts())
print(cleaned_df['DataSource'].value_counts())
print(cleaned_df['YearStart'].value_counts().sort_index())
print(cleaned_df.isnull().sum())

(3972, 10)
Topic
Cardiovascular Disease                   1464
Chronic Obstructive Pulmonary Disease    1356
Diabetes                                  678
Asthma                                    474
Name: count, dtype: int64
DataSource
BRFSS                     1728
NVSS                      1632
CMS Part A Claims Data     612
Name: count, dtype: int64
YearStart
2019    993
2020    777
2021    993
2022    777
2023    432
Name: count, dtype: int64
YearStart                0
LocationAbbr             0
DataSource               0
Topic                    0
Question                 0
DataValueType            0
DataValueAlt           121
LowConfidenceLimit     121
HighConfidenceLimit    121
Stratification1          0
dtype: int64

In [20]:
cleaned_df.dtypes

YearStart               int64
LocationAbbr           object
DataSource             object
Topic                  object
Question               object
DataValueType          object
DataValueAlt           object
LowConfidenceLimit     object
HighConfidenceLimit    object
Stratification1        object
dtype: object

In [21]:
import os
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)



conditions_bkup = {
    'Asthma': {
        'prevalence': {'source':'BRFSS', 'question': 'Current asthma among adults'},
        'mortality': {'source': 'NVSS', 'question':'Asthma mortality among all people, underlying cause'},
        'hospitalization': None
    },
    'Cardiovascular Disease': {
        'prevalence': {'source': 'BRFSS', 'question':'High blood pressure among adults'},
        'mortality': {'source': 'NVSS', 'question':'Diseases of the heart mortality among all people, underlying cause'},
        'hospitalization': {'source': 'CMS Part A Claims Data', 'question':'Hospitalization for heart failure as principal diagnosis, Medicare-beneficiaries aged 65 years and older'}
    },
    'Chronic Obstructive Pulmonary Disease': {
        'prevalence':{'source': 'BRFSS', 'question':'Chronic obstructive pulmonary disease among adults'},
        'mortality':{'source': 'NVSS', 'question':'Chronic obstructive pulmonary disease mortality among adults aged 45 years and older, underlying cause'},
        'hospitalization':{'source': 'CMS Part A Claims Data', 'question':'Hospitalization for chronic obstructive pulmonary disease as principal diagnosis, Medicare-beneficiaries aged 65 years and older'}
    },
    'Diabetes': {
        'prevalence':{'source': 'BRFSS', 'question':'Diabetes among adults'},
        'mortality':{'source': 'NVSS', 'question':'Diabetes mortality among all people, underlying or contributing cause'},
        'hospitalization': None
    }
}

conditions = {
    'Asthma': {
        'prevalence': {'source':'BRFSS', 'question': 'Current asthma among adults'},
        'mortality': {'source': 'NVSS', 'question':'Asthma mortality among all people, underlying cause'},
        'hospitalization': None
    },
    'Cardiovascular Disease': {
        'prevalence': {'source': 'BRFSS', 'question':'High blood pressure among adults'},
        'mortality': {'source': 'NVSS', 'question':'Diseases of the heart mortality among all people, underlying cause'},
        'hospitalization': {'source': 'CMS Part A Claims Data', 'question':'Hospitalization for heart failure as principal diagnosis, Medicare-beneficiaries aged 65 years and older'}
    },
    'Chronic Obstructive Pulmonary Disease': {
        'prevalence':{'source': 'BRFSS', 'question':'Chronic obstructive pulmonary disease among adults'},
        'mortality':{'source': 'NVSS', 'question':'Chronic obstructive pulmonary disease mortality among adults aged 45 years and older, underlying cause'},
        'hospitalization':{'source': 'CMS Part A Claims Data', 'question':'Hospitalization for chronic obstructive pulmonary disease as principal diagnosis, Medicare-beneficiaries aged 65 years and older'}
    },
    'Diabetes': {
        'prevalence':{'source': 'BRFSS', 'question':'Diabetes among adults'},
        'mortality':{'source': 'NVSS', 'question':'Diabetes mortality among all people, underlying or contributing cause'},
        'hospitalization': None
    }
}

In [22]:
pieces = []
for key, value in conditions.items():
    for inner_key, inner_value in value.items():
        if inner_value is None:
            continue
        slice_df = cleaned_df.loc[(cleaned_df['Topic'] == key) & (cleaned_df['DataSource'] == inner_value['source']) & (cleaned_df['Question'] == inner_value['question'])].copy()
        slice_df['measurement'] = inner_key
        pieces.append(slice_df)

In [23]:
filtered = pd.concat(pieces, ignore_index=True)

In [24]:
filtered

,YearStart,LocationAbbr,DataSource,Topic,Question,DataValueType,DataValueAlt,LowConfidenceLimit,HighConfidenceLimit,Stratification1,measurement
0,2020,OK,BRFSS,Asthma,Current asthma among adults,Age-adjusted Prevalence,12.1,11.0,13.3,Overall,prevalence
1,2019,KY,BRFSS,Asthma,Current asthma among adults,Age-adjusted Prevalence,10.4,9.3,11.5,Overall,prevalence
2,2020,LA,BRFSS,Asthma,Current asthma among adults,Age-adjusted Prevalence,8.8,7.7,10.0,Overall,prevalence
3,2021,MO,BRFSS,Asthma,Current asthma among adults,Age-adjusted Prevalence,10.5,9.6,11.4,Overall,prevalence
4,2022,IA,BRFSS,Asthma,Current asthma among adults,Age-adjusted Prevalence,9.7,8.9,10.7,Overall,prevalence
...,...,...,...,...,...,...,...,...,...,...,...
2191,2019,MN,NVSS,Diabetes,"Diabetes mortality among all people, underlying or contributing cause",Age-adjusted Rate,87.9,85.6,90.1,Overall,mortality
2192,2019,PA,NVSS,Diabetes,"Diabetes mortality among all people, underlying or contributing cause",Age-adjusted Rate,62.7,61.5,63.9,Overall,mortality
2193,2022,MT,NVSS,Diabetes,"Diabetes mortality among all people, underlying or contributing cause",Age-adjusted Rate,89.2,84.3,94,Overall,mortality
2194,2021,TX,NVSS,Diabetes,"Diabetes mortality among all people, underlying or contributing cause",Age-adjusted Rate,124.3,123,125.6,Overall,mortality
2195,2020,VT,NVSS,Diabetes,"Diabetes mortality among all people, underlying or contributing cause",Age-adjusted Rate,98,91.4,104.6,Overall,mortality

In [25]:
print(filtered.shape)
print(filtered['measurement'].value_counts())
print(filtered['Topic'].value_counts())

(2196, 11)
measurement
prevalence         972
mortality          816
hospitalization    408
Name: count, dtype: int64
Topic
Chronic Obstructive Pulmonary Disease    678
Cardiovascular Disease                   570
Asthma                                   474
Diabetes                                 474
Name: count, dtype: int64

In [26]:
print(filtered['DataValueAlt'].dtype)

object

In [27]:
filtered.dtypes

YearStart               int64
LocationAbbr           object
DataSource             object
Topic                  object
Question               object
DataValueType          object
DataValueAlt           object
LowConfidenceLimit     object
HighConfidenceLimit    object
Stratification1        object
measurement            object
dtype: object

In [28]:
filtered['DataValueAlt'] = pd.to_numeric(filtered['DataValueAlt'], errors='coerce')
filtered['LowConfidenceLimit'] = pd.to_numeric(filtered['LowConfidenceLimit'], errors='coerce')
filtered['HighConfidenceLimit'] = pd.to_numeric(filtered['HighConfidenceLimit'], errors='coerce')

In [29]:
panel_df = filtered.pivot_table(index=['LocationAbbr','YearStart','Topic'], columns='measurement', values=['DataValueAlt', 'LowConfidenceLimit', 'HighConfidenceLimit'])

In [30]:
panel_df

                                                                DataValueAlt  \
measurement                                                  hospitalization
LocationAbbr YearStart Topic
AK           2019      Asthma                                            NaN
                       Cardiovascular Disease                           9.80
                       Chronic Obstructive Pulmonary Disease            3.66
                       Diabetes                                          NaN
             2020      Asthma                                            NaN
...                                                                      ...
WY           2022      Diabetes                                          NaN
             2023      Asthma                                            NaN
                       Cardiovascular Disease                            NaN
                       Chronic Obstructive Pulmonary Disease             NaN
                       Diabetes                                          NaN

                                                                        \
measurement                                                  mortality
LocationAbbr YearStart Topic
AK           2019      Asthma                                      NaN
                       Cardiovascular Disease                    129.7
                       Chronic Obstructive Pulmonary Disease      81.7
                       Diabetes                                   45.8
             2020      Asthma                                      NaN
...                                                                ...
WY           2022      Diabetes                                  105.1
             2023      Asthma                                      NaN
                       Cardiovascular Disease                      NaN
                       Chronic Obstructive Pulmonary Disease       NaN
                       Diabetes                                    NaN

                                                                         \
measurement                                                  prevalence
LocationAbbr YearStart Topic
AK           2019      Asthma                                      10.5
                       Cardiovascular Disease                      32.8
                       Chronic Obstructive Pulmonary Disease        4.6
                       Diabetes                                     7.2
             2020      Asthma                                       9.8
...                                                                 ...
WY           2022      Diabetes                                     8.1
             2023      Asthma                                      10.1
                       Cardiovascular Disease                      28.1
                       Chronic Obstructive Pulmonary Disease        6.6
                       Diabetes                                     9.4

                                                             HighConfidenceLimit  \
measurement                                                      hospitalization
LocationAbbr YearStart Topic
AK           2019      Asthma                                                NaN
                       Cardiovascular Disease                              10.55
                       Chronic Obstructive Pulmonary Disease                4.12
                       Diabetes                                              NaN
             2020      Asthma                                                NaN
...                                                                          ...
WY           2022      Diabetes                                              NaN
             2023      Asthma                                                NaN
                       Cardiovascular Disease                                NaN
                       Chronic Obstructive Pulmonary Disease                 NaN
                       Diabetes                                              NaN

                                                                        \
measurement                                                  mortality
LocationAbbr YearStart Topic
AK           2019      Asthma                                      NaN
                       Cardiovascular Disease                    138.9
                       Chronic Obstructive Pulmonary Disease      93.9
                       Diabetes                                   51.2
             2020      Asthma                                      NaN
...                                                                ...
WY           2022      Diabetes                                  112.6
             2023      Asthma                                      NaN
                       Cardiovascular Disease                      NaN
                       Chronic Obstructive Pulmonary Disease       NaN
                       Diabetes                                    NaN

                                                                         \
measurement                                                  prevalence
LocationAbbr YearStart Topic
AK           2019      Asthma                                      12.4
                       Cardiovascular Disease                      35.3
                       Chronic Obstructive Pulmonary Disease        5.6
                       Diabetes                                     8.5
             2020      Asthma                                      11.5
...                                                                 ...
WY           2022      Diabetes                                     9.0
             2023      Asthma                                      11.5
                       Cardiovascular Disease                      29.7
                       Chronic Obstructive Pulmonary Disease        7.7
                       Diabetes                                    10.5

                                                             LowConfidenceLimit  \
measurement                                                     hospitalization
LocationAbbr YearStart Topic
AK           2019      Asthma                                               NaN
                       Cardiovascular Disease                              9.05
                       Chronic Obstructive Pulmonary Disease               3.20
                       Diabetes                                             NaN
             2020      Asthma                                               NaN
...                                                                         ...
WY           2022      Diabetes                                             NaN
             2023      Asthma                                               NaN
                       Cardiovascular Disease                               NaN
                       Chronic Obstructive Pulmonary Disease                NaN
                       Diabetes                                             NaN

                                                                        \
measurement                                                  mortality
LocationAbbr YearStart Topic
AK           2019      Asthma                                      NaN
                       Cardiovascular Disease                    120.5
                       Chronic Obstructive Pulmonary Disease      69.4
                       Diabetes                                   40.4
             2020      Asthma                                      NaN
...                                                                ...
WY           2022      Diabetes                                   97.5
             2023      Asthma                                      NaN
                       Cardiovascular Disease                      NaN
                       Chronic Obstructive Pulmonary Disease       NaN
                       Diabetes                                    NaN


measurement                                                  prevalence
LocationAbbr YearStart Topic
AK           2019      Asthma                                       8.9
                       Cardiovascular Disease                      30.4
                       Chronic Obstructive Pulmonary Disease        3.7
                       Diabetes                                     6.1
             2020      Asthma                                       8.4
...                                                                 ...
WY           2022      Diabetes                                     7.3
             2023      Asthma                                       8.9
                       Cardiovascular Disease                      26.5
                       Chronic Obstructive Pulmonary Disease        5.7
                       Diabetes                                     8.5

[1057 rows x 9 columns]

In [31]:
val = filtered.pivot_table(index=['LocationAbbr','YearStart','Topic'], columns='measurement', values='DataValueAlt')
lo  = filtered.pivot_table(index=['LocationAbbr','YearStart','Topic'], columns='measurement', values='LowConfidenceLimit')
hi  = filtered.pivot_table(index=['LocationAbbr','YearStart','Topic'], columns='measurement', values='HighConfidenceLimit')

In [32]:
val

measurement                                                   hospitalization  \
LocationAbbr YearStart Topic
AK           2019      Asthma                                             NaN
                       Cardiovascular Disease                            9.80
                       Chronic Obstructive Pulmonary Disease             3.66
                       Diabetes                                           NaN
             2020      Asthma                                             NaN
...                                                                       ...
WY           2022      Diabetes                                           NaN
             2023      Asthma                                             NaN
                       Cardiovascular Disease                             NaN
                       Chronic Obstructive Pulmonary Disease              NaN
                       Diabetes                                           NaN

measurement                                                   mortality  \
LocationAbbr YearStart Topic
AK           2019      Asthma                                       NaN
                       Cardiovascular Disease                     129.7
                       Chronic Obstructive Pulmonary Disease       81.7
                       Diabetes                                    45.8
             2020      Asthma                                       NaN
...                                                                 ...
WY           2022      Diabetes                                   105.1
             2023      Asthma                                       NaN
                       Cardiovascular Disease                       NaN
                       Chronic Obstructive Pulmonary Disease        NaN
                       Diabetes                                     NaN

measurement                                                   prevalence
LocationAbbr YearStart Topic
AK           2019      Asthma                                       10.5
                       Cardiovascular Disease                       32.8
                       Chronic Obstructive Pulmonary Disease         4.6
                       Diabetes                                      7.2
             2020      Asthma                                        9.8
...                                                                  ...
WY           2022      Diabetes                                      8.1
             2023      Asthma                                       10.1
                       Cardiovascular Disease                       28.1
                       Chronic Obstructive Pulmonary Disease         6.6
                       Diabetes                                      9.4

[1057 rows x 3 columns]

In [33]:
lo

measurement                                                   hospitalization  \
LocationAbbr YearStart Topic
AK           2019      Asthma                                             NaN
                       Cardiovascular Disease                            9.05
                       Chronic Obstructive Pulmonary Disease             3.20
                       Diabetes                                           NaN
             2020      Asthma                                             NaN
...                                                                       ...
WY           2022      Diabetes                                           NaN
             2023      Asthma                                             NaN
                       Cardiovascular Disease                             NaN
                       Chronic Obstructive Pulmonary Disease              NaN
                       Diabetes                                           NaN

measurement                                                   mortality  \
LocationAbbr YearStart Topic
AK           2019      Asthma                                       NaN
                       Cardiovascular Disease                     120.5
                       Chronic Obstructive Pulmonary Disease       69.4
                       Diabetes                                    40.4
             2020      Asthma                                       NaN
...                                                                 ...
WY           2022      Diabetes                                    97.5
             2023      Asthma                                       NaN
                       Cardiovascular Disease                       NaN
                       Chronic Obstructive Pulmonary Disease        NaN
                       Diabetes                                     NaN

measurement                                                   prevalence
LocationAbbr YearStart Topic
AK           2019      Asthma                                        8.9
                       Cardiovascular Disease                       30.4
                       Chronic Obstructive Pulmonary Disease         3.7
                       Diabetes                                      6.1
             2020      Asthma                                        8.4
...                                                                  ...
WY           2022      Diabetes                                      7.3
             2023      Asthma                                        8.9
                       Cardiovascular Disease                       26.5
                       Chronic Obstructive Pulmonary Disease         5.7
                       Diabetes                                      8.5

[1057 rows x 3 columns]

In [34]:
hi

measurement                                                   hospitalization  \
LocationAbbr YearStart Topic
AK           2019      Asthma                                             NaN
                       Cardiovascular Disease                           10.55
                       Chronic Obstructive Pulmonary Disease             4.12
                       Diabetes                                           NaN
             2020      Asthma                                             NaN
...                                                                       ...
WY           2022      Diabetes                                           NaN
             2023      Asthma                                             NaN
                       Cardiovascular Disease                             NaN
                       Chronic Obstructive Pulmonary Disease              NaN
                       Diabetes                                           NaN

measurement                                                   mortality  \
LocationAbbr YearStart Topic
AK           2019      Asthma                                       NaN
                       Cardiovascular Disease                     138.9
                       Chronic Obstructive Pulmonary Disease       93.9
                       Diabetes                                    51.2
             2020      Asthma                                       NaN
...                                                                 ...
WY           2022      Diabetes                                   112.6
             2023      Asthma                                       NaN
                       Cardiovascular Disease                       NaN
                       Chronic Obstructive Pulmonary Disease        NaN
                       Diabetes                                     NaN

measurement                                                   prevalence
LocationAbbr YearStart Topic
AK           2019      Asthma                                       12.4
                       Cardiovascular Disease                       35.3
                       Chronic Obstructive Pulmonary Disease         5.6
                       Diabetes                                      8.5
             2020      Asthma                                       11.5
...                                                                  ...
WY           2022      Diabetes                                      9.0
             2023      Asthma                                       11.5
                       Cardiovascular Disease                       29.7
                       Chronic Obstructive Pulmonary Disease         7.7
                       Diabetes                                     10.5

[1057 rows x 3 columns]

In [35]:
lo = lo.add_suffix('_lo')
hi = hi.add_suffix('_hi')

In [36]:
lo

measurement                                                   hospitalization_lo  \
LocationAbbr YearStart Topic
AK           2019      Asthma                                                NaN
                       Cardiovascular Disease                               9.05
                       Chronic Obstructive Pulmonary Disease                3.20
                       Diabetes                                              NaN
             2020      Asthma                                                NaN
...                                                                          ...
WY           2022      Diabetes                                              NaN
             2023      Asthma                                                NaN
                       Cardiovascular Disease                                NaN
                       Chronic Obstructive Pulmonary Disease                 NaN
                       Diabetes                                              NaN

measurement                                                   mortality_lo  \
LocationAbbr YearStart Topic
AK           2019      Asthma                                          NaN
                       Cardiovascular Disease                        120.5
                       Chronic Obstructive Pulmonary Disease          69.4
                       Diabetes                                       40.4
             2020      Asthma                                          NaN
...                                                                    ...
WY           2022      Diabetes                                       97.5
             2023      Asthma                                          NaN
                       Cardiovascular Disease                          NaN
                       Chronic Obstructive Pulmonary Disease           NaN
                       Diabetes                                        NaN

measurement                                                   prevalence_lo
LocationAbbr YearStart Topic
AK           2019      Asthma                                           8.9
                       Cardiovascular Disease                          30.4
                       Chronic Obstructive Pulmonary Disease            3.7
                       Diabetes                                         6.1
             2020      Asthma                                           8.4
...                                                                     ...
WY           2022      Diabetes                                         7.3
             2023      Asthma                                           8.9
                       Cardiovascular Disease                          26.5
                       Chronic Obstructive Pulmonary Disease            5.7
                       Diabetes                                         8.5

[1057 rows x 3 columns]

In [37]:
panel_df = pd.concat([val, lo, hi], axis=1)

In [38]:
panel_df

measurement                                                   hospitalization  \
LocationAbbr YearStart Topic
AK           2019      Asthma                                             NaN
                       Cardiovascular Disease                            9.80
                       Chronic Obstructive Pulmonary Disease             3.66
                       Diabetes                                           NaN
             2020      Asthma                                             NaN
...                                                                       ...
WY           2022      Diabetes                                           NaN
             2023      Asthma                                             NaN
                       Cardiovascular Disease                             NaN
                       Chronic Obstructive Pulmonary Disease              NaN
                       Diabetes                                           NaN

measurement                                                   mortality  \
LocationAbbr YearStart Topic
AK           2019      Asthma                                       NaN
                       Cardiovascular Disease                     129.7
                       Chronic Obstructive Pulmonary Disease       81.7
                       Diabetes                                    45.8
             2020      Asthma                                       NaN
...                                                                 ...
WY           2022      Diabetes                                   105.1
             2023      Asthma                                       NaN
                       Cardiovascular Disease                       NaN
                       Chronic Obstructive Pulmonary Disease        NaN
                       Diabetes                                     NaN

measurement                                                   prevalence  \
LocationAbbr YearStart Topic
AK           2019      Asthma                                       10.5
                       Cardiovascular Disease                       32.8
                       Chronic Obstructive Pulmonary Disease         4.6
                       Diabetes                                      7.2
             2020      Asthma                                        9.8
...                                                                  ...
WY           2022      Diabetes                                      8.1
             2023      Asthma                                       10.1
                       Cardiovascular Disease                       28.1
                       Chronic Obstructive Pulmonary Disease         6.6
                       Diabetes                                      9.4

measurement                                                   hospitalization_lo  \
LocationAbbr YearStart Topic
AK           2019      Asthma                                                NaN
                       Cardiovascular Disease                               9.05
                       Chronic Obstructive Pulmonary Disease                3.20
                       Diabetes                                              NaN
             2020      Asthma                                                NaN
...                                                                          ...
WY           2022      Diabetes                                              NaN
             2023      Asthma                                                NaN
                       Cardiovascular Disease                                NaN
                       Chronic Obstructive Pulmonary Disease                 NaN
                       Diabetes                                              NaN

measurement                                                   mortality_lo  \
LocationAbbr YearStart Topic
AK           2019      Asthma                                          NaN
                       Cardiovascular Disease                        120.5
                       Chronic Obstructive Pulmonary Disease          69.4
                       Diabetes                                       40.4
             2020      Asthma                                          NaN
...                                                                    ...
WY           2022      Diabetes                                       97.5
             2023      Asthma                                          NaN
                       Cardiovascular Disease                          NaN
                       Chronic Obstructive Pulmonary Disease           NaN
                       Diabetes                                        NaN

measurement                                                   prevalence_lo  \
LocationAbbr YearStart Topic
AK           2019      Asthma                                           8.9
                       Cardiovascular Disease                          30.4
                       Chronic Obstructive Pulmonary Disease            3.7
                       Diabetes                                         6.1
             2020      Asthma                                           8.4
...                                                                     ...
WY           2022      Diabetes                                         7.3
             2023      Asthma                                           8.9
                       Cardiovascular Disease                          26.5
                       Chronic Obstructive Pulmonary Disease            5.7
                       Diabetes                                         8.5

measurement                                                   hospitalization_hi  \
LocationAbbr YearStart Topic
AK           2019      Asthma                                                NaN
                       Cardiovascular Disease                              10.55
                       Chronic Obstructive Pulmonary Disease                4.12
                       Diabetes                                              NaN
             2020      Asthma                                                NaN
...                                                                          ...
WY           2022      Diabetes                                              NaN
             2023      Asthma                                                NaN
                       Cardiovascular Disease                                NaN
                       Chronic Obstructive Pulmonary Disease                 NaN
                       Diabetes                                              NaN

measurement                                                   mortality_hi  \
LocationAbbr YearStart Topic
AK           2019      Asthma                                          NaN
                       Cardiovascular Disease                        138.9
                       Chronic Obstructive Pulmonary Disease          93.9
                       Diabetes                                       51.2
             2020      Asthma                                          NaN
...                                                                    ...
WY           2022      Diabetes                                      112.6
             2023      Asthma                                          NaN
                       Cardiovascular Disease                          NaN
                       Chronic Obstructive Pulmonary Disease           NaN
                       Diabetes                                        NaN

measurement                                                   prevalence_hi
LocationAbbr YearStart Topic
AK           2019      Asthma                                          12.4
                       Cardiovascular Disease                          35.3
                       Chronic Obstructive Pulmonary Disease            5.6
                       Diabetes                                         8.5
             2020      Asthma                                          11.5
...                                                                     ...
WY           2022      Diabetes                                         9.0
             2023      Asthma                                          11.5
                       Cardiovascular Disease                          29.7
                       Chronic Obstructive Pulmonary Disease            7.7
                       Diabetes                                        10.5

[1057 rows x 9 columns]

In [39]:
panel_df = panel_df.reset_index()

In [40]:
panel_df

measurement,LocationAbbr,YearStart,Topic,hospitalization,mortality,prevalence,hospitalization_lo,mortality_lo,prevalence_lo,hospitalization_hi,mortality_hi,prevalence_hi
0,AK,2019,Asthma,NaN,NaN,10.5,NaN,NaN,8.9,NaN,NaN,12.4
1,AK,2019,Cardiovascular Disease,9.80,129.7,32.8,9.05,120.5,30.4,10.55,138.9,35.3
2,AK,2019,Chronic Obstructive Pulmonary Disease,3.66,81.7,4.6,3.20,69.4,3.7,4.12,93.9,5.6
3,AK,2019,Diabetes,NaN,45.8,7.2,NaN,40.4,6.1,NaN,51.2,8.5
4,AK,2020,Asthma,NaN,NaN,9.8,NaN,NaN,8.4,NaN,NaN,11.5
...,...,...,...,...,...,...,...,...,...,...,...,...
1052,WY,2022,Diabetes,NaN,105.1,8.1,NaN,97.5,7.3,NaN,112.6,9.0
1053,WY,2023,Asthma,NaN,NaN,10.1,NaN,NaN,8.9,NaN,NaN,11.5
1054,WY,2023,Cardiovascular Disease,NaN,NaN,28.1,NaN,NaN,26.5,NaN,NaN,29.7
1055,WY,2023,Chronic Obstructive Pulmonary Disease,NaN,NaN,6.6,NaN,NaN,5.7,NaN,NaN,7.7
1056,WY,2023,Diabetes,NaN,NaN,9.4,NaN,NaN,8.5,NaN,NaN,10.5

In [41]:
panel.to_csv("../data/clean/panel_verify.csv", index=False)

In [42]:
print('US' in panel_df['LocationAbbr'].values)
print(panel_df['LocationAbbr'].nunique())

False
54

### MNAR = Missing Not At Random — the fact that a value is missing is itself informative.